//! What the runtime insists on before it lets KMS near its master secret: a key
//! whose policy nobody can change, which releases the secret to this enclave's
//! measurements and to nothing else.
//!
//! ## Why the enclave checks
//!
//! The key policy is the whole security control ([`super::kms`]): KMS releases
//! the secret only to an attestation whose PCR0 and PCR16 the policy names. But
//! a policy is only as good as its last edit. One that lets the account change
//! it lets an administrator — or whoever holds their credentials — rewrite it to
//! "let me decrypt", fetch the sealed copy from SSM and read the secret. So the
//! enclave reads the key's metadata, its policy and its grants straight from
//! KMS, over TLS that ends inside the enclave, and refuses to mint or open under
//! a key that fails any of:
//!
//! - **Generated by KMS, in one region, managed by the customer.** Imported
//!   material, or a custom key store, means a copy of the key exists outside
//!   KMS. A multi-region key has replicas, each with a policy of its own.
//! - **A policy that grants nothing it does not need.** Reading the key, listing
//!   its grants, and deleting it — on purpose: deletion destroys the secret, it
//!   cannot reveal it, and a deployment must be able to end. `Decrypt` and
//!   `GenerateDataKey` only on this enclave's PCR0 and PCR16. Anything else —
//!   `PutKeyPolicy`, `CreateGrant`, `ReEncrypt*`, a wildcard — is refused, and
//!   with it every way to edit the policy: the policy also bounds what any IAM
//!   policy in the account can grant on this key.
//! - **No grants.** A grant made before the policy was locked would outlive
//!   the lock.
//!
//! What is left to an attacker is to destroy: delete the key, the SSM copy or
//! the store, and the enclave cannot boot. Nothing here makes it boot *wrong*.
//!
//! The check is an allow-list, deliberately. A policy is a small language with
//! inversions, wildcards and `IfExists` operators; deciding in general whether
//! one leaks is hard, and deciding whether one stays inside a short list of
//! shapes is not.
//!
//! ## What it costs
//!
//! A policy that can never change names one PCR0 and one PCR16 forever, so a new
//! runtime or a new guest cannot open a store made by the old one. Upgrades need
//! a hand-over this runtime does not have yet.

use anyhow::{bail, Context, Result};
use aws_sdk_kms::types::{KeyManagerType, KeyMetadata, KeySpec, KeyUsageType, OriginType};
use serde_json::{Map, Value};

/// Actions a policy may grant to anyone, unconditioned. None of them can change
/// the policy, add a grant or see the secret.
const UNCONDITIONED: &[&str] = &[
    "kms:describekey",
    "kms:getkeypolicy",
    "kms:getkeyrotationstatus",
    "kms:listgrants",
    "kms:listkeypolicies",
    "kms:listresourcetags",
    "kms:schedulekeydeletion",
    "kms:cancelkeydeletion",
];

/// Actions that release the secret: only on this enclave's measurements.
const RELEASING: &[&str] = &["kms:decrypt", "kms:generatedatakey"];

const PCR0: &str = "kms:recipientattestation:pcr0";
const PCR16: &str = "kms:recipientattestation:pcr16";

/// The key itself: material that never left KMS, one copy of it, ours to govern.
pub fn check_key(meta: &KeyMetadata) -> Result<()> {
    if meta.origin() != Some(&OriginType::AwsKms) {
        bail!(
            "its key material has origin {:?}, not AWS_KMS. Imported material or a custom key \
             store means a copy of the key exists outside KMS, where no policy reaches it.",
            meta.origin()
        );
    }
    if meta.key_manager() != Some(&KeyManagerType::Customer) {
        bail!("it is not a customer managed key, so its policy is not one a deployment chose");
    }
    if meta.multi_region() == Some(true) {
        bail!(
            "it is a multi-region key. Every replica has a policy of its own, and this enclave \
             can read only one of them."
        );
    }
    if meta.key_spec() != Some(&KeySpec::SymmetricDefault)
        || meta.key_usage() != Some(&KeyUsageType::EncryptDecrypt)
    {
        bail!(
            "it is {:?} for {:?}, not a symmetric encryption key",
            meta.key_spec(),
            meta.key_usage()
        );
    }
    Ok(())
}

/// The key's policy: nothing that could change it, and the secret for this
/// enclave's `pcr0` and `pcr16` alone.
pub fn check_policy(policy: &str, pcr0: &[u8; 48], pcr16: &[u8; 48]) -> Result<()> {
    let doc: Value = serde_json::from_str(policy).context("the key policy is not JSON")?;
    let doc = doc
        .as_object()
        .context("the key policy is not a JSON object")?;
    only_fields(doc, &["Version", "Id", "Statement"])?;
    // The other version has no policy variables; refusing it costs nothing.
    if doc.get("Version").and_then(Value::as_str) != Some("2012-10-17") {
        bail!("the key policy is not version 2012-10-17");
    }
    let statements = match doc.get("Statement") {
        Some(Value::Array(all)) => all.iter().collect(),
        Some(one @ Value::Object(_)) => vec![one],
        _ => bail!("the key policy has no statements"),
    };
    let (pcr0, pcr16) = (hex::encode(pcr0), hex::encode(pcr16));
    for (i, statement) in statements.into_iter().enumerate() {
        let sid = statement.get("Sid").and_then(Value::as_str).unwrap_or("");
        check_statement(statement, &pcr0, &pcr16)
            .with_context(|| format!("key policy statement {i} {sid:?}"))?;
    }
    Ok(())
}

fn check_statement(statement: &Value, pcr0: &str, pcr16: &str) -> Result<()> {
    let statement = statement.as_object().context("is not an object")?;
    only_fields(
        statement,
        &[
            "Sid",
            "Effect",
            "Principal",
            "NotPrincipal",
            "Action",
            "NotAction",
            "Resource",
            "NotResource",
            "Condition",
        ],
    )?;
    match statement.get("Effect").and_then(Value::as_str) {
        // A denial only ever takes away.
        Some("Deny") => return Ok(()),
        Some("Allow") => {}
        other => bail!("has Effect {other:?}"),
    }
    for inverted in ["NotPrincipal", "NotAction", "NotResource"] {
        if statement.contains_key(inverted) {
            bail!("allows with {inverted}, which grants everything it does not name");
        }
    }
    let mut releases = false;
    for action in strings(statement.get("Action").context("allows no Action")?)? {
        let lower = action.to_ascii_lowercase();
        if RELEASING.contains(&lower.as_str()) {
            releases = true;
        } else if !UNCONDITIONED.contains(&lower.as_str()) {
            bail!(
                "allows {action}. A key this enclave trusts allows reading it, deleting it, and \
                 releasing the secret to this enclave — nothing that could change who gets it."
            );
        }
    }
    if releases {
        pinned_to(statement.get("Condition"), pcr0, pcr16)?;
    }
    Ok(())
}

/// A releasing statement must pin both registers, to these values, with an
/// exact operator. Any other condition beside them only narrows it further.
fn pinned_to(condition: Option<&Value>, pcr0: &str, pcr16: &str) -> Result<()> {
    let condition = condition
        .and_then(Value::as_object)
        .context("releases the secret with no condition")?;
    let (mut has_pcr0, mut has_pcr16) = (false, false);
    for (operator, keys) in condition {
        // Exact operators only. An `IfExists` variant passes a request that
        // carries no attestation at all, and a `ForAnyValue`/`ForAllValues`
        // qualifier changes what matching means.
        if !operator.eq_ignore_ascii_case("StringEquals")
            && !operator.eq_ignore_ascii_case("StringEqualsIgnoreCase")
        {
            continue;
        }
        let keys = keys
            .as_object()
            .with_context(|| format!("has a malformed {operator} condition"))?;
        for (key, values) in keys {
            let lower = key.to_ascii_lowercase();
            let (want, found) = match lower.as_str() {
                PCR0 => (pcr0, &mut has_pcr0),
                PCR16 => (pcr16, &mut has_pcr16),
                _ => continue,
            };
            let values = strings(values)?;
            // Every value, because a list admits any one of them.
            if values.is_empty() || values.iter().any(|v| !v.eq_ignore_ascii_case(want)) {
                bail!(
                    "releases the secret on {key} {values:?}, and this enclave's is {want}. A key \
                     that releases to another enclave too is not one this enclave can trust."
                );
            }
            *found = true;
        }
    }
    if !(has_pcr0 && has_pcr16) {
        bail!("releases the secret without pinning both PCR0 and PCR16 to this enclave's");
    }
    Ok(())
}

fn only_fields(object: &Map<String, Value>, known: &[&str]) -> Result<()> {
    match object.keys().find(|k| !known.contains(&k.as_str())) {
        Some(unknown) => bail!("has a field this check does not know, {unknown:?}"),
        None => Ok(()),
    }
}

/// A policy value that may be one string or a list of them.
fn strings(value: &Value) -> Result<Vec<&str>> {
    match value {
        Value::String(one) => Ok(vec![one.as_str()]),
        Value::Array(many) => many
            .iter()
            .map(|v| v.as_str().context("lists something that is not a string"))
            .collect(),
        _ => bail!("has a value that is neither a string nor a list of strings"),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    const P0: [u8; 48] = [0xa0; 48];
    const P16: [u8; 48] = [0x16; 48];

    /// The policy merlin-infra sets: the account may read and delete the key,
    /// the enclave's role may read it and, on its measurements, use it.
    fn locked() -> Value {
        json!({
            "Version": "2012-10-17",
            "Statement": [
                {
                    "Sid": "ReadAndDelete",
                    "Effect": "Allow",
                    "Principal": { "AWS": "arn:aws:iam::111122223333:root" },
                    "Action": [
                        "kms:DescribeKey", "kms:GetKeyPolicy", "kms:GetKeyRotationStatus",
                        "kms:ListGrants", "kms:ListResourceTags", "kms:ScheduleKeyDeletion",
                        "kms:CancelKeyDeletion"
                    ],
                    "Resource": "*"
                },
                {
                    "Sid": "Release",
                    "Effect": "Allow",
                    "Principal": { "AWS": "arn:aws:iam::111122223333:role/parent" },
                    "Action": ["kms:Decrypt", "kms:GenerateDataKey"],
                    "Resource": "*",
                    "Condition": { "StringEqualsIgnoreCase": {
                        "kms:RecipientAttestation:PCR0": hex::encode(P0),
                        "kms:RecipientAttestation:PCR16": hex::encode(P16)
                    }}
                }
            ]
        })
    }

    fn check(policy: &Value) -> Result<()> {
        check_policy(&policy.to_string(), &P0, &P16)
    }

    fn refused(policy: &Value, why: &str) {
        let err = format!("{:#}", check(policy).expect_err("should be refused"));
        assert!(err.contains(why), "expected {why:?} in: {err}");
    }

    #[test]
    fn the_locked_policy_is_accepted() {
        check(&locked()).unwrap();
    }

    #[test]
    fn a_policy_anyone_can_edit_is_refused() {
        for action in [
            "kms:PutKeyPolicy",
            "kms:*",
            "kms:Put*",
            "kms:CreateGrant",
            "*",
        ] {
            let mut policy = locked();
            policy["Statement"][0]["Action"]
                .as_array_mut()
                .unwrap()
                .push(json!(action));
            refused(&policy, &format!("allows {action}"));
        }
    }

    /// ReEncryptFrom would move the ciphertext under a key the caller controls.
    #[test]
    fn re_encrypting_is_refused() {
        let mut policy = locked();
        policy["Statement"][0]["Action"] = json!("kms:ReEncryptFrom");
        refused(&policy, "allows kms:ReEncryptFrom");
    }

    #[test]
    fn releasing_without_the_measurements_is_refused() {
        let mut policy = locked();
        policy["Statement"][1]
            .as_object_mut()
            .unwrap()
            .remove("Condition");
        refused(&policy, "no condition");

        let mut policy = locked();
        policy["Statement"][1]["Condition"]["StringEqualsIgnoreCase"]
            .as_object_mut()
            .unwrap()
            .remove("kms:RecipientAttestation:PCR16");
        refused(&policy, "without pinning both");
    }

    #[test]
    fn releasing_to_another_enclave_is_refused() {
        let mut policy = locked();
        policy["Statement"][1]["Condition"]["StringEqualsIgnoreCase"]
            ["kms:RecipientAttestation:PCR16"] = json!(hex::encode([0x17; 48]));
        refused(&policy, "this enclave's is");

        // A list admits any one of its values.
        let mut policy = locked();
        policy["Statement"][1]["Condition"]["StringEqualsIgnoreCase"]
            ["kms:RecipientAttestation:PCR0"] = json!([hex::encode(P0), hex::encode([0x01; 48])]);
        refused(&policy, "this enclave's is");
    }

    /// `IfExists` passes a request with no attestation at all.
    #[test]
    fn an_if_exists_pin_does_not_count() {
        let mut policy = locked();
        let pins = policy["Statement"][1]["Condition"]
            .as_object_mut()
            .unwrap()
            .remove("StringEqualsIgnoreCase")
            .unwrap();
        policy["Statement"][1]["Condition"]["StringEqualsIgnoreCaseIfExists"] = pins;
        refused(&policy, "without pinning both");
    }

    /// The same release, unconditioned, in a second statement.
    #[test]
    fn every_releasing_statement_must_be_pinned() {
        let mut policy = locked();
        policy["Statement"].as_array_mut().unwrap().push(json!({
            "Effect": "Allow",
            "Principal": { "AWS": "*" },
            "Action": "kms:Decrypt",
            "Resource": "*"
        }));
        refused(&policy, "statement 2");
    }

    #[test]
    fn inversions_are_refused() {
        for inverted in ["NotAction", "NotPrincipal", "NotResource"] {
            let mut policy = locked();
            policy["Statement"][0][inverted] = json!("kms:Decrypt");
            refused(&policy, inverted);
        }
    }

    #[test]
    fn denials_and_extra_conditions_are_fine() {
        let mut policy = locked();
        policy["Statement"].as_array_mut().unwrap().push(json!({
            "Effect": "Deny",
            "Principal": "*",
            "NotAction": "kms:*",
            "Resource": "*"
        }));
        policy["Statement"][1]["Condition"]["StringEquals"] =
            json!({ "kms:EncryptionContext:environment": "production" });
        // Upper-case hex, a single statement object, odd action case: all one policy.
        policy["Statement"][1]["Condition"]["StringEqualsIgnoreCase"]
            ["kms:RecipientAttestation:PCR0"] = json!(hex::encode(P0).to_uppercase());
        policy["Statement"][1]["Action"] = json!(["KMS:Decrypt", "kms:generatedatakey"]);
        check(&policy).unwrap();
        check(&json!({ "Version": "2012-10-17", "Statement": locked()["Statement"][1] })).unwrap();
    }

    #[test]
    fn what_it_cannot_read_is_refused() {
        refused(
            &json!({ "Version": "2008-10-17", "Statement": [] }),
            "2012-10-17",
        );
        let mut policy = locked();
        policy["Statement"][0]["Unknown"] = json!(1);
        refused(&policy, "\"Unknown\"");
        assert!(check_policy("not json", &P0, &P16).is_err());
    }

    fn metadata() -> aws_sdk_kms::types::builders::KeyMetadataBuilder {
        KeyMetadata::builder()
            .key_id("k")
            .origin(OriginType::AwsKms)
            .key_manager(KeyManagerType::Customer)
            .multi_region(false)
            .key_spec(KeySpec::SymmetricDefault)
            .key_usage(KeyUsageType::EncryptDecrypt)
    }

    #[test]
    fn only_a_single_region_kms_generated_customer_key_is_trusted() {
        check_key(&metadata().build().unwrap()).unwrap();
        for (meta, why) in [
            (metadata().origin(OriginType::External), "origin"),
            (metadata().origin(OriginType::AwsCloudhsm), "origin"),
            (
                metadata().key_manager(KeyManagerType::Aws),
                "customer managed",
            ),
            (metadata().multi_region(true), "multi-region"),
            (metadata().key_spec(KeySpec::Rsa2048), "symmetric"),
        ] {
            let err = format!("{:#}", check_key(&meta.build().unwrap()).unwrap_err());
            assert!(err.contains(why), "expected {why:?} in: {err}");
        }
    }
}
